### ISSUE TITLE
[Table]: Error state for table

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#130] opened 2019-04-01 21:51 UTC

**Comment by matsgothe** [comment] 2019-04-02 06:59
@scottdickerson can you provide a quick summary of the use-case here.
- What is an Error state
- Example(s) of table error states
- The severity levels

**Comment by scottdickerson** [comment] 2019-04-02 14:05
sure, the usecase is we are loading the table with data and the data load fails.  This is our current approach (we just show the error message in the table), perhaps we just need to get your review and approval. Let us know if we need to change anything:

![image](https://user-images.githubusercontent.com/6663002/55408815-6437af80-5526-11e9-8bb5-ccf65774045c.png)

**Comment by matsgothe** [comment] 2019-04-02 14:24
This design should define the default behavior for generic errors on the table. 
The preferred behavior is that the client provides the reason of error and any resolutions to the cause and the severity of the error. The table may provide the dialog to show this text.
The other default is for the platform to provide a generic error text that 'something failed' is there is an internal or error that the client did not provide a cause of.
The alternate approach would be for the client to take control and provide a custom response with resolution actions like, retry, do this, do that.

**Comment by matsgothe** [comment] 2019-04-02 14:25
@amymillett is that a story with existing dialogs that we can summarize here to outline the behavior.

**Comment by matsgothe** [comment] 2019-04-02 14:27
Most imploringly I think is the visual decision if that is a dialog on top, or a a error section in-line with the table. Is there an error scheme for the Carbon table that we can adopt?

**Comment by amymillett** [comment] 2019-04-08 19:22
@scottdickerson @matsgothe For situations where the table data does not load at all, I would use the same design as the empty table state:

![Screen Shot 2019-04-08 at 2 14 07 PM](https://user-images.githubusercontent.com/48336859/55750332-acfcd600-5a08-11e9-93b8-cd5a1badb6c9.png)

If there's some sort of action they can take, like "contact IBM" or something like that we can include a button, otherwise it can just be a generic error message.

![Screen Shot 2019-04-08 at 2 16 56 PM](https://user-images.githubusercontent.com/48336859/55750520-141a8a80-5a09-11e9-85eb-17ddaa493a5f.png)

I'll try to address more specific errors in https://github.com/IBM/carbon-addons-iot-react/issues/129 and https://github.com/IBM/carbon-addons-iot-react/issues/128

**Comment by matsgothe** [comment] 2019-04-09 07:32
@amymillett I think the Table

**Comment by amymillett** [comment] 2019-04-09 21:08
@scottdickerson @lukefirth We could definitely do something other than the bee, not sure if I like the giant X though. Especially since an X like that usually means "close" or "dismiss"

These are some dialogs Cynthia and I recommended for the Platform awhile back, so we could use similar iconography:

<img width="337" alt="Screen Shot 2019-04-09 at 4 04 29 PM" src="https://user-images.githubusercontent.com/48336859/55835215-32ec5000-5ae1-11e9-800c-acf7e6059d81.png">

Which would look more like this:
<img width="640" alt="Screen Shot 2019-04-09 at 4 06 35 PM" src="https://user-images.githubusercontent.com/48336859/55835312-78108200-5ae1-11e9-9955-d7a4a870bdbf.png">
<img width="632" alt="Screen Shot 2019-04-09 at 4 07 08 PM" src="https://user-images.githubusercontent.com/48336859/55835344-8ced1580-5ae1-11e9-837e-470095c7aef9.png">

**Comment by amymillett** [comment] 2019-04-09 21:12
And in regards to your note above Luke, I see what you mean about this needing to be coupled with a general notification... I am also thinking that can be accomplished with toast notifications from Carbon.

<img width="433" alt="Screen Shot 2019-04-09 at 4 11 46 PM" src="https://user-images.githubusercontent.com/48336859/55835740-41873700-5ae2-11e9-93c4-943aedb74a36.png">

**Comment by lukefirth** [comment] 2019-04-10 08:54
@amymillett I *really* like those examples for this. I like both, but especially this one:
![image](https://user-images.githubusercontent.com/30671949/55865030-88723c80-5b75-11e9-92ea-ba9f336e0962.png) Because it looks like a warning/alert (although that is a touch weird I guess with the fact that error and warning are different in the modal examples and it would be nice to be consistent).

---

However I would personally leave this:
![image](https://user-images.githubusercontent.com/30671949/55865046-8c9e5a00-5b75-11e9-8725-45b0734b20b7.png)

For a rarer occasion, we may want to put into the table for 'you don't have access' to these resources etc. The only reason I feel we might be best not to use this second one is that to me at least, the icon denotes 'barred access' 'go no further' kind of thing.
![image](https://user-images.githubusercontent.com/30671949/55865409-354cb980-5b76-11e9-8551-62b4d7e81da7.png)

----

As for the toasts - personally I think the call or whatever that created the error may not be bound to the table component itself (eg: it could be an error that causes a lot of things to happen, and the table being empty is one). So while we should address in guidance that the teams use toasts for errors in general, perhaps rather than building anything into the table to deliver it.

**Comment by davidicus** [comment] 2020-06-02 15:24
completed.

**Comment by matsgothe** [comment] 2020-06-04 08:09
This is a core table feature.

**Comment by lukefirth** [comment] 2020-06-04 14:50
@matsgothe , did you mean to reopen an issue that is marked as 'completed'?
If so, have you/can you confirm that the completed work does not meet the set requirement outlined in the issue? 

@davidicus would it be possible to link an example/place/PR that is tied to the completion here so @matsgothe can verify 👍

**Closed** 2020-06-04 15:20 UTC
