### ISSUE TITLE
[Header]: App Switcher support to switch main app when within header

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#193] opened 2019-04-23 14:42 UTC
Add app switcher to the top left of the Header

**Comment by davidicus** [comment] 2019-09-30 04:31
Spec is outlined here:

https://ibm.invisionapp.com/share/SNNZ29ZAY6V#/screens/319167299
and
https://ibm.invisionapp.com/share/D6NZ4C0PUN9#/screens/319188836_Navigation_Panel_-_Usage

**Comment by davidicus** [comment] 2019-09-30 04:36
Dupe of #58

**Closed by davidicus** 2019-09-30 04:36 UTC
Labels: :computer:  Development
