### ISSUE TITLE
[StatefulTable] when embedded StatefulTable widget in ComposedModal, selectAll not work

### ISSUE THREAD

**Issue by zhaozhuo813** [IBM/carbon-addons-iot-react#1192] opened 2020-05-15 13:39 UTC
### Describe the bug
When embedded StatefulTable widget in ComposedModal, selectAll not work. If choose selectAll, other statefultable select all will enabled. see the screenshot below. When we click select all in the table at front, then the other table at the back has been enabled and selected.

![image](https://user-images.githubusercontent.com/65387028/82056553-b3be4800-96f4-11ea-86df-9cca672c6b54.png)

### Expected behavior

When choose selectall in table which embedded in composedModal,  the table rows can be selected correctly

### Environment/versions:

- OS: [MacOS]
- Browser: [all]
- `carbon-addons-iot-react` version: [e.g. `v2.62.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Out product will be release at September.

**Comment by tay1orjones** [comment] 2020-07-23 18:46
Duplicate of #1084

**Closed by tay1orjones** 2020-07-23 18:46 UTC
Labels: status: needs triage :mag:, type: bug :bug:
