### ISSUE TITLE
TableCards don't support links in expanded rows

### ISSUE THREAD

**Issue by JoelArmendariz** [IBM/carbon-addons-iot-react#1215] opened 2020-05-22 19:53 UTC
### Describe the bug

TableCards support click-able links in their rows, but we need to support in expanded rows as well.

### Expected behavior

TableCard expanded rows should support linkTemplate hrefs as clickable links.

![Screen Shot 2020-05-22 at 2 52 39 PM](https://user-images.githubusercontent.com/53092833/82704772-e8258d00-9c3b-11ea-9786-031b21dac51b.png)

**Comment by davidicus** [comment] 2020-05-26 23:55
Duplicate of #1216

**Closed by davidicus** 2020-05-26 23:55 UTC
Labels: :bug:  Bug
