### ISSUE TITLE
[Table] Cannot properly see the row overflow options on Table when in RTL mode

### ISSUE THREAD

**Issue by camilasb** [IBM/carbon-addons-iot-react#573] opened 2019-09-30 12:15 UTC
Steps:

1. Open the Storybook
2. Click on Table component
3. Click on RTL tab and check the RTL toggle
4. Click on one of the overflow buttons in the rows
Actual Result: Actions on overflow cannot be properly seen
Expected Result: Overflow options should be displayed to the right so they could be seen
Maybe the menu should open left in that case.
 
![image](https://user-images.githubusercontent.com/20360162/65877689-a66d6c80-e362-11e9-966f-0de783e0185a.png)

**Comment by davidicus** [comment] 2020-06-02 20:15
this is not stale. There is a newer duplicate and i will close once located.

**Comment by tay1orjones** [comment] 2020-07-23 18:22
Duplicate of #1197

**Comment by tay1orjones** [comment] 2020-07-23 18:22
Resolved via https://github.com/IBM/carbon-addons-iot-react/pull/1357

**Closed by tay1orjones** 2020-07-23 18:22 UTC
Labels: type: RTL :arrow_left:, type: bug :bug:
