### ISSUE TITLE
ValueCard: should not truncate number values by default, and should dynamically size fonts to available width

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#1090] opened 2020-04-14 16:57 UTC
### Summary
The Value Card when it shows values, it needs to more dynamically size it's font size to the available space, we have lots of temporary workarounds to try and work around this issue, but we should really simplify how it handles multiple values at different sizes and labels, and support a much wider range of possible fonts

Here's a workaround, sometime we wrap to two lines, and sometimes we for numbers shorten the number to 'K', 'M' or 'G' for thousand million, etc, but customers have complained about this.

![image](https://user-images.githubusercontent.com/6663002/79252217-e13e7a00-7e46-11ea-90bd-8f2661b186c8.png)

**Additional context**
I think @lukefirth and @CynZhang have updated designs to handle this.

### Specific timeline issues / requests

This is an important issue for us in Monitor

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by scottdickerson** [comment] 2020-05-01 21:04
https://github.ibm.com/Watson-IoT/pal-tracking/issues/260 Detailed Design

**Comment by tay1orjones** [comment] 2020-06-03 20:23
Duplicate of #1276

**Closed by tay1orjones** 2020-06-03 20:23 UTC
Labels: type: enhancement :bulb:
