### ISSUE TITLE
Stateful Table Filtering not working, when filtered for only 0.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#480] opened 2019-08-09 16:22 UTC
Hello Team,

I am using Stateful component and seeing that table data is not filtering the values with only "0".
In the Storybook I can see the same issue happening, where if I click on filter icon and enter 0 in the Number column and press enter, the first row which has only 0 is getting filtered out and unable to find that in the displayed data. It seems to be a bug.

![image](https://user-images.githubusercontent.com/22093326/62793634-a3d36100-baef-11e9-9aca-2fb50d69a0bd.png)

![image](https://user-images.githubusercontent.com/22093326/62793672-bf3e6c00-baef-11e9-8b1c-05ef1db43550.png)

 
https://carbon-addons-iot-react.com/?selectedKind=Table&selectedStory=Stateful%20Example%20with%20row%20nesting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

I am using  "carbon-addons-iot-react": "1.53.1",

**Comment by kalyanixraut** [comment] 2019-09-18 07:03
Hi Team, can you please update on this issue. When is the fix planned for this.

**Comment by tay1orjones** [comment] 2019-09-25 16:29
Thanks for opening an issue for this! I'd like to see our filtering functions improved to meet this use case. 

This hasn't been added to a release plan/milestone yet, though this should be a fairly straightforward change if you're interested in contributing a fix. I believe the problem is within `filterData()`

https://github.com/IBM/carbon-addons-iot-react/blob/82d2219eb7b1ae2ed455067b6244ad60f166a1f3/src/components/Table/tableReducer.js#L29-L47

**Comment by scottdickerson** [comment] 2020-02-05 18:51
this is fixed now

**Closed by scottdickerson** 2020-02-05 18:51 UTC
