### ISSUE TITLE
[SimpleList] in the storybook, selection of items is additive

### ISSUE THREAD

**Issue by jm986** [IBM/carbon-addons-iot-react#1171] opened 2020-05-09 18:33 UTC
### Describe the bug

When items are selected in the story book the previous selected item is not unslected

### To Reproduce

1. Go to 'https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-simplelist--basic'
2. Click on 'Item 1'
3. Click on 'Item 2'
4. both items show as selected

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

![2020-05-09_11-32-52](https://user-images.githubusercontent.com/63420281/81482019-e8a83780-91e8-11ea-8497-115e3a274f37.png)

**Comment by tay1orjones** [comment] 2020-05-11 14:09
Thanks for reporting this - it's present all the way up to v2.75.3 as well

Duplicate of #1149

**Comment by tay1orjones** [comment] 2020-05-11 14:09
Duplicate of #1149

**Closed by tay1orjones** 2020-05-11 14:09 UTC
Labels: :bug:  Bug
