### ISSUE TITLE
[Table] Add indeterminate state for row nesting checkboxes

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#216] opened 2019-04-29 14:46 UTC
# Issue Details

## Detailed description

1) Add the ability for checkboxes on table rows to display the "indeterminate" state (horizontal line) to indicate that one or more child rows are selected

2) Update the stateful table to have this behavior by default (when a child row is checked but the parent row is not, show the indeterminate state)

**Comment by davidicus** [comment] 2019-10-07 15:21
Duplicate of #124. Closing

**Closed by davidicus** 2019-10-07 15:21 UTC
Labels: :hammer:  Enhancement
