### ISSUE TITLE
[ValueCard] attribute layout rules

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1247] opened 2020-06-01 12:47 UTC
[internal issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/260)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an extension of the logic for the existing value cards (including outlook for other types in future).
> 
> **What is the rationale for this contribution.**
> The value cards have a number of issues open around them today on the topic of how they (at varying sizes) manage varying scales of content such as long values, long units, wrapping etc. This contribution puts forward a framework to think and talk about all of these elements, as well as a proposal for how we can address these needs.
> 
> **Detail the intended behavior**
> At a high level, we identify that a value card has a set X & Y space for its payload. Inside there will be the primary value along with supporting elements such as the unit, threshold alerts, variance, labels and more.
> 
> **The overall intended behavior to put it in a few points is:**
> 
> * The supporting elements will take up as much space as they require based on their content
> * The value will adjust its font size to balloon up or shrink down to fill any remaining space on a single line.
> * If it is not possible to fit its full value on a single line at a 20pt, it will then begin to wrap.
> 
> This can be seen in more detail as such:
> ![Basic anatomy and scenarios](https://media.github.ibm.com/user/684/files/3ffbb600-516c-11ea-9211-cb4cf9ff3364)
> 
> Supporting image 1: Value cards with multiple values.
> ![Multi-value cards](https://media.github.ibm.com/user/684/files/468a2d80-516c-11ea-9770-3bf5bc41ddbf)
> 
> Supporting image 2: Examples of this logic applied to some cases with varying unit size and varying value length at different levels of complexity:
> ![Examples](https://media.github.ibm.com/user/684/files/82c18c00-5174-11ea-97e3-b52d67e12c72)

Be sure to check out comments in internal thread.

**Comment by tay1orjones** [comment] 2020-06-03 20:22
Duplicate of #1276

**Closed by tay1orjones** 2020-06-03 20:22 UTC
