### ISSUE TITLE
[Application switcher] support light theme in UI Shell right panel with switcher

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#663] opened 2019-10-31 05:25 UTC
### Summary

https://carbon-addons-iot-react.com/?path=/story/watson-iot-header--header-action-buttons-with-dropdowns
The header right panel has dark background, how can it be made to be shown with light background as in below screen capture.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/22093326/67921159-deb7d300-fbcc-11e9-9e25-e594bb69ff4c.png">
 
<sub>[Internal issue #56](https://github.ibm.com/Watson-IoT/pal-tracking/issues/56)</sub>

**Comment by tay1orjones** [comment] 2019-11-01 19:40
The background color style is set via the `.bx--header-panel` selector and can be overridden.

@lukefirth are we moving forward to deviate from Carbon with a light background instead of the Carbon default dark background? 

[Design site guidance shows light](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/patterns/navigation-global/usage)

**Comment by lukefirth** [comment] 2019-11-01 20:12
Design site is out of date, currently, it shows what is the original Carbon design for the 'app switcher' panel. However Carbon has since changed this design to be the same treatment as the other panels (dark, with a different selected state than the blue X shown in the original Carbon design and above).

- I will need to confirm w/Guidea who are designing the suite level navigation which makes use of this, but my personal opinion is that we should update with the newer Carbon design.

**Comment by tay1orjones** [comment] 2019-11-04 18:49
> we should update with the newer Carbon design

If so, this should be as simple as deleting/removing any overrides we have in our codebase in regards to this component. Let us know which way and we can likely get this closed out quickly.

**Comment by davidicus** [comment] 2019-11-08 02:06
I believe we are in line with Carbon currently. And if confirmed by Luke, it will be the IoT site that needs to be updated. 

http://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-actions-and-right-panel

**Comment by tay1orjones** [comment] 2019-11-18 16:16
On hold, pending direction from the internal PAL team

[Internal issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/56)

**Comment by davidicus** [comment] 2020-02-26 21:43
closing as we currently support white panel for application switcher.

**Closed by davidicus** 2020-02-26 21:43 UTC
Labels: :hammer:  Enhancement, on hold
