### ISSUE TITLE
[Package.json] Failing yarn and yarn test in Windows 10 env

### ISSUE THREAD

**Issue by sunilkotiyaibm** [IBM/carbon-addons-iot-react#770] opened 2019-12-05 17:22 UTC
### Describe the bug
1. yarn command is getting failed on carbon-addons-iot-react,  
```
C:\Users\SunilKotiya\CarbonReactWorkspace\TableResize\carbon-addons-iot-react>yarn
yarn install v1.21.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@semantic-release/commit-analyzer/-/commit-analyzer-7.0.0-beta-.2.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\SunilKotiya\\CarbonReactWorkspace\\TableResize\\carbon-addons-iot-react\\yarn-error.log".
```

After removing dependency @carbon/charts" and "@carbon/charts-react", yarn command getting successfully.

2. On executing yarn test, it is failing on , below is the error log.
```
PS C:\Users\SunilKotiya\carbon-addons-iot-react> yarn test                                                                                                                                      yarn run v1.21.0
$ yarn test:a11y && yarn test:base
$ cross-env TZ=America/Chicago jest --forceExit --testPathPattern=".*\.a11y\.js(x)?"
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\SunilKotiya\carbon-addons-iot-react
  260 files checked.
  testMatch: C:/Users/SunilKotiya/carbon-addons-iot-react/**/__tests__/**/*.js?(x), C:/Users/SunilKotiya/carbon-addons-iot-react/**\?(*.)(spec|test).js?(x), C:/Users/SunilKotiya/carbon-addons-iot-react/**\?(*.)test.a11y.js?(x) - 2 matches
  testPathIgnorePatterns: \\config\\, \\lib\\ - 253 matches
  testRegex:  - 0 matches
Pattern: .*\.a11y\.js(x)? - 0 matches
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

### To Reproduce

git clone https://github.com/IBM/carbon-addons-iot-react.git
cd carbon-addons-iot-react
c:\users\carbon-addons-iot-react>yarn

> Please create a reduced test case in CodeSandbox:

### Expected behavior

1. yarn command should be executed 
2. yarn test should display test results with coverage

### Environment/versions:

- OS: Windows 10
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.7.1`]
 - node :  10.15.3 and above till 12.13.1
### Additional context
screenshot attached

### Specific timeline issues / requests

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by tay1orjones** [comment] 2019-12-05 20:03
I'm unable to reproduce on `master` using Windows WSL w/ Ubuntu 18.04. `yarn` install succeeds, as well as `yarn test`

Are you running the commands within the WSL ubuntu shell? Note that project may not build in powershell or the default windows cmd shell, even with Git for Windows installed.

**Comment by sunilkotiyaibm** [comment] 2019-12-06 07:29
> @sunilkotiyaibm I'm unable to reproduce on `master` using Windows WSL w/ Ubuntu 18.04. `yarn` install succeeds, as well as `yarn test`
> 
> The output you gave above appears to be the result of an environment that doesn't support the regex/glob syntax in the commands. Are you running the commands within the WSL ubuntu shell/application? Note that project may not build in powershell or the default windows cmd shell, even with Git for Windows installed.

@tay1orjones I tried on Ubuntu 18.04.02 LTS (install on windows 10) on master branch, but face the same issue, screenshot shared over slack. But it's working on mac. 
![Ubuntu_18 04 02](https://user-images.githubusercontent.com/56038154/70304522-1ba86280-1828-11ea-810f-b300b4ffac42.png)

**Comment by tay1orjones** [comment] 2019-12-06 20:58
We confirmed this to be resolved on current `master`, thanks to [a recent upgrade of the semantic release dependencies.](https://github.com/IBM/carbon-addons-iot-react/blob/ee6468760bb4af1c38ad99b329e9afb65180c2a8/yarn.lock#L2555) 

The url for this particular dependency was invalid in `yarn.lock`. I'm still unsure why it resolved in some environments and not in others, could be related to the yarn caches of these different environments. Either way, the upgrade removed the invalid url for the url of the newer version.

**Closed** 2019-12-06 20:58 UTC
Labels: :bug:  Bug
